### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by eth0izzle** [kmrbolas/ProjetoBayer#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@cluster0-mfkxs.mongodb.net` in file [/app.js](https://github.com/kmrbolas/ProjetoBayer/blob/master/app.js)

**Comment by ghost** [comment]
thanks for the warning eh0izzle, but since this is just a school project is not really a big deal.
